INSERT INTO categories
    (category_name)
VALUES
    ('HTML'),
    ('CSS'),
    ('JavaScript'),
    ('TypeScript'),
    ('PHP'),
    ('Java'),
    ('Python'),
    ('Csharp'),
    ('Ruby'),
    ('Assembler'),
    ('C'),
    ('Cpp'),
    ('SQL'),
    ('Kotlin'),
    ('Swift');

INSERT INTO roles (role_name) VALUES ('Admin'), ('User');

INSERT INTO users
    (username, email, password, role_id)
VALUES
    ('julzaw', 'julzaw@gmail.com', '$2y$10$L8F2pcsrEbLlmtfq0LFgiORQ1eRVR3iy5HYgg7i74jhI5J0c0uzki', 2),
    ('amawoz', 'amawoz@gmail.com', '$2y$10$ejaCaOZT3TZzR5Nk34EPHe4DpRwjdq16wA309/Loh9dhkYhOXj0oa', 2),
    ('korcza', 'korcza@gmail.com', '$2y$10$O1TN24QU8ubAMji4NxV9tuIXeVi4NLcNMTygZfvMnyCy9VLIVAdaW', 2),
    ('ariprz', 'ariprz@gmail.com', '$2y$10$e88X23SgQwX3bz3ebERA6OJHOJNvWAfQsKru1hHw4MHkdPUa.BoqK', 2),
    ('olabor', 'olabor@gmail.com', '$2y$10$//.wOrxtrNzsHlTh/7C.EuBQA8hujrPxUGUoY9uctmQ2dickCwXmW', 1);

INSERT INTO posts
    (title, content, created_at, is_published, user_id, category_id)
VALUES
    # Java
    ('Dlaczego warto uczyć się Javy?', 'Java to jeden z najbardziej popularnych języków programowania na świecie. Jest używany w aplikacjach desktopowych, webowych oraz mobilnych. Dzięki swojej przenośności („Write Once, Run Anywhere”) programy napisane w Javie mogą działać na różnych platformach bez konieczności zmian w kodzie. Świetnym przykładem zastosowania Javy jest Android, gdzie Java była przez wiele lat głównym językiem programowania. Dodatkowo, silne typowanie Javy pomaga unikać wielu błędów już na etapie kompilacji, co czyni ją idealnym wyborem dla dużych, skalowalnych projektów. Bogata biblioteka standardowa oraz wiele dostępnych frameworków, takich jak Spring czy Hibernate, sprawiają, że Java jest nie tylko łatwa w nauce, ale również potężnym narzędziem do tworzenia różnorodnych aplikacji. Jej popularność i ogromna społeczność oznaczają, że można znaleźć odpowiedzi na większość problemów programistycznych oraz łatwo znaleźć pracę jako programista Javy', '2024-11-18 10:00:00', true, 1, 6),
    ('Podstawy programowania w Javie', 'Java jest językiem obiektowym, co oznacza, że większość kodu opiera się na koncepcji obiektów i klas. Aby rozpocząć swoją przygodę z Javą, warto poznać podstawowe konstrukcje języka, takie jak klasy, metody, pętle (for, while), warunki (if, switch) oraz podstawowe typy danych (int, double, String). Dodatkowo, Java oferuje wyjątkowo przejrzystą obsługę wyjątków, co pozwala programiście łatwo zarządzać błędami w kodzie. Warto również zrozumieć koncepcję dziedziczenia, polimorfizmu i enkapsulacji, które są podstawą paradygmatu obiektowego.', '2024-10-18 12:54:00', true, 3, 6),
    ('Java Collections Framework', 'Kolekcje w Javie to zestaw klas i interfejsów do przechowywania danych w różnych strukturach, takich jak listy, mapy, zestawy czy kolejki. Dzięki nim programista może efektywnie zarządzać danymi, sortować je, przeszukiwać oraz wykonywać wiele operacji bez potrzeby ręcznego implementowania tych funkcji. Framework kolekcji obsługuje struktury takie jak ArrayList, HashMap, TreeSet czy PriorityQueue. Każda z nich ma swoje unikalne zastosowanie, np. ArrayList jest szybka w dostępie do danych, ale mniej wydajna w operacjach wstawiania i usuwania elementów w środku listy. Znajomość Java Collections Framework to kluczowy krok w rozwoju programisty, który chce pisać bardziej wydajne i przejrzyste aplikacje', '2024-11-18 10:30:00', true, 2, 6),
    ('Wzorce projektowe w Javie', 'Zastosowanie wzorców projektowych, takich jak Singleton czy Factory, pozwala lepiej organizować kod i unikać błędów. W Javie wiele wzorców jest implementowanych przy użyciu standardowych bibliotek.','2024-11-17 18:00:00',  true, 2, 6),
    ('Spring Boot - Wprowadzenie', 'Spring Boot to framework, który znacząco upraszcza tworzenie aplikacji w Javie. Dzięki Spring Boot można rozpocząć projekt bez potrzeby ręcznej konfiguracji i długich przygotowań. Automatyczna konfiguracja pozwala na szybkie uruchomienie aplikacji z minimalną ilością kodu, a wbudowany serwer, taki jak Tomcat, umożliwia łatwe wdrożenie aplikacji. Spring Boot wspiera takie technologie jak Spring Data (praca z bazami danych), Spring Security (autoryzacja i uwierzytelnianie) czy Spring Cloud (mikrousługi). Idealnie nadaje się zarówno dla początkujących, jak i zaawansowanych programistów, którzy chcą tworzyć nowoczesne, skalowalne aplikacje.', '2024-11-16 21:15:00', true, 3, 6),
    ('Java Stream API', 'Stream API w Javie to potężne narzędzie do przetwarzania danych w sposób deklaratywny. Umożliwia to wykonywanie operacji na kolekcjach i innych źródłach danych w postaci łańcucha operacji, takich jak mapowanie, filtrowanie, sortowanie czy zbieranie wyników. Stream API pozwala na przetwarzanie danych w sposób bardziej elegancki i czytelny w porównaniu do tradycyjnych pętli. Dzięki zastosowaniu operacji takich jak "map()", "filter()" czy "collect()", kod staje się bardziej zwięzły i łatwiejszy do zrozumienia. Dodatkowo, dzięki możliwości pracy równoległej (za pomocą metody "parallelStream()"), Stream API pozwala na optymalizację aplikacji w przypadku przetwarzania dużych zbiorów danych. Stream API jest jednym z najnowszych narzędzi w Javie, które zrewolucjonizowało sposób pracy z kolekcjami i danymi.', '2024-11-14 08:30:00', true, 5, 6),
    ('Tworzenie aplikacji webowej z Spring Boot', 'Spring Boot to doskonałe narzędzie do tworzenia aplikacji webowych w Javie. Dzięki wbudowanemu serwerowi aplikacji (np. Tomcat), aplikacja Spring Boot uruchamia się zaledwie poprzez uruchomienie pojedynczego pliku JAR. Spring Boot wspiera tworzenie RESTful API, a jego integracja z Spring MVC umożliwia budowanie aplikacji webowych opartych na architekturze Model-View-Controller. Framework zapewnia łatwą integrację z bazami danych za pomocą Spring Data JPA oraz wsparcie dla szerokiej gamy technologii frontendowych, takich jak Angular czy React. Dodatkowo, Spring Boot oferuje gotowe mechanizmy do obsługi autentykacji i autoryzacji użytkowników, co ułatwia budowanie aplikacji bez konieczności pisania od podstaw rozbudowanego systemu zabezpieczeń.', '2024-11-17 11:30:00', true, 2, 6),
    ('Spring Boot i baza danych', 'Spring Boot oferuje zaawansowane mechanizmy ułatwiające pracę z bazami danych. Dzięki Spring Data JPA, programiści mogą łatwo łączyć aplikację z relacyjnymi bazami danych, takimi jak PostgreSQL, MySQL czy H2. Spring Boot automatycznie konfiguruje połączenie z bazą danych na podstawie prostych ustawień w pliku "application.properties". Dzięki temu, zamiast pisać skomplikowaną konfigurację, programiści mogą skupić się na logice aplikacji. Dodatkowo, Spring Boot obsługuje transakcje, co umożliwia zarządzanie operacjami na bazach danych w sposób bezpieczny i spójny. Framework zapewnia również łatwą integrację z narzędziami do migracji baz danych, takimi jak Flyway czy Liquibase.', '2024-11-16 09:00:00', true, 3, 6),
    ('Spring Boot i bezpieczeństwo aplikacji', 'Bezpieczeństwo aplikacji to jeden z kluczowych elementów w budowie nowoczesnych systemów. Spring Boot oferuje kompleksowe rozwiązania w zakresie zabezpieczeń aplikacji dzięki Spring Security. Framework ten wspiera różne mechanizmy uwierzytelniania użytkowników, takie jak logowanie za pomocą nazwy użytkownika i hasła, OAuth2, oraz JWT (JSON Web Tokens). Dzięki wbudowanym funkcjom, takim jak kontrola dostępu do zasobów (role-based access control) oraz zabezpieczenia przed atakami typu CSRF i XSS, programiści mogą szybko zaimplementować system autoryzacji. Spring Boot pozwala również na łatwą integrację z zewnętrznymi systemami uwierzytelniania, co umożliwia tworzenie aplikacji z wysokim poziomem bezpieczeństwa.', '2024-11-15 13:30:00', true, 4, 6),
    ('Spring Boot i mikroserwisy', 'Spring Boot jest jednym z najczęściej wybieranych narzędzi do tworzenia aplikacji opartych na mikroserwisach. Dzięki Spring Cloud, Spring Boot pozwala na łatwą konfigurację i zarządzanie mikroserwisami, które mogą być uruchamiane w różnych środowiskach, takich jak chmura, kontenery Docker czy Kubernetes. Mikroserwisy to podejście do projektowania aplikacji, które zakłada podział na małe, autonomiczne usługi, które mogą być rozwijane, testowane i wdrażane niezależnie. Spring Boot zapewnia wbudowane wsparcie dla konfiguracji, monitorowania, obsługi komunikacji między mikroserwisami, oraz rozproszonych transakcji, co czyni go idealnym narzędziem do pracy z tą architekturą.', '2024-11-14 15:00:00', true, 5, 6),

    # PHP
    ('Wprowadzenie do PHP', 'PHP to jeden z najpopularniejszych języków skryptowych używanych do tworzenia dynamicznych stron internetowych. Dzięki swojej prostocie i elastyczności jest często pierwszym wyborem dla początkujących programistów webowych. PHP pozwala na łatwe łączenie z bazami danych, obsługę formularzy oraz dynamiczne generowanie treści. Wielką zaletą PHP jest ogromna liczba gotowych bibliotek i frameworków, takich jak Laravel czy Symfony, które przyspieszają tworzenie bardziej zaawansowanych aplikacji. W połączeniu z HTML, CSS i JavaScript, PHP umożliwia tworzenie interaktywnych i responsywnych stron WWW. Język ten obsługuje wiele systemów baz danych, takich jak MySQL, PostgreSQL czy SQLite, co czyni go niezastąpionym narzędziem w budowie złożonych aplikacji internetowych', '2024-11-15 08:00:00',true, 1, 5),
    ('Praca z bazami danych w PHP', 'PHP oferuje wiele narzędzi do pracy z bazami danych, w tym MySQL, PostgreSQL i SQLite. Jednym z najpopularniejszych sposobów jest wykorzystanie rozszerzenia PDO (PHP Data Objects), które zapewnia bezpieczne i efektywne metody komunikacji z bazą danych. Dzięki PDO możemy korzystać z zapytań przygotowanych, co chroni aplikację przed atakami typu SQL Injection.', '2024-11-18 15:30:00', true, 2, 5),
    ('PHP 8.1 - Nowe funkcje', 'PHP 8.1 wprowadza wiele nowości, które upraszczają pisanie bardziej czytelnego i wydajnego kodu. Jedną z nich są typy wyliczeniowe (Enums), które pozwalają na definiowanie precyzyjnych zestawów wartości dla zmiennych. Fibers to kolejna duża zmiana - pozwalają one na pisanie kodu asynchronicznego w bardziej liniowy sposób, co jest szczególnie przydatne w aplikacjach wymagających dużej wydajności. Oprócz tego poprawiona wersja JIT (Just-In-Time Compiler) przyspiesza działanie kodu, co ma znaczenie w projektach o dużym obciążeniu. PHP 8.1 to krok w kierunku nowoczesnego programowania webowego', '2024-11-18 19:37:00', true, 3, 5),
    ('Framework Laravel', 'Laravel to jeden z najpopularniejszych frameworków PHP, znany ze swojej prostoty i elegancji. Dzięki wbudowanemu ORM (Eloquent), systemowi migracji baz danych oraz silnikowi szablonów Blade, tworzenie aplikacji webowych staje się szybkie i przyjemne. Laravel wspiera również zaawansowane funkcje, takie jak middleware, kolejki zadań czy integracja z narzędziami DevOps, co czyni go odpowiednim wyborem dla profesjonalnych programistów. Dokumentacja Laravela jest uznawana za jedną z najlepszych, co sprawia, że nauka frameworka jest łatwa nawet dla osób, które dopiero zaczynają swoją przygodę z PHP', '2024-11-18 21:20:00', true, 3, 5),
    ('Praca z sesjami w PHP', 'Sesje w PHP pozwalają na przechowywanie informacji o użytkowniku pomiędzy żądaniami HTTP. Dzięki sesjom możesz zarządzać stanem aplikacji, przechowywać dane o użytkowniku, takie jak logowanie, koszyk zakupowy czy preferencje. Sesje w PHP są łatwe w użyciu i pozwalają na zachowanie danych między stronami.', '2024-11-17 12:25:00', true, 2, 5),
    ('PHP 8.0 - Co się zmieniło?', 'Wersja PHP 8.0 wprowadziła wiele istotnych zmian, takich jak: <ol><li>Operator "match" - Alternatywa dla instrukcji "switch".</li><li>Named Arguments - Możliwość przekazywania parametrów funkcji w dowolnej kolejności.</li><li>JIT (Just-In-Time Compilation) - Znaczne przyspieszenie wykonywania kodu w porównaniu do wcześniejszych wersji.</li></ol>', '2024-11-20 11:05:00', true, 5, 5),

    # HTML
    ('Podstawy HTML: Jak zacząć?','HTML, czyli HyperText Markup Language, to podstawowy język, który służy do tworzenia struktury stron internetowych. Każda strona internetowa wymaga jakiejś formy struktury, a HTML jest odpowiedzialny za jej zdefiniowanie. Za pomocą HTML możemy tworzyć nagłówki, akapity, linki, obrazy oraz wiele innych elementów. Warto zacząć od nauki podstawowych tagów, takich jak &lt;html&gt;, &lt;head&gt;, &lt;body&lt;gt oraz &lt;h1&gt;, &lt;p&gt;, &lt;a&gt;. Aby strona była dostępna dla jak najszerszego grona odbiorców, warto również pamiętać o dobrych praktykach SEO, takich jak odpowiednia semantyka i używanie tagów opisujących zawartość strony.', '2024-11-19 12:00:00', true, 1, 1),
    ('Jak działa struktura dokumentu HTML?', 'Dokument HTML jest zbudowany z hierarchicznych tagów, które definiują jego strukturę. Na samej górze znajduje się deklaracja &lt;!DOCTYPE html&gt;, która mówi przeglądarkom, jakiego rodzaju dokument ma zostać wyświetlony. Następnie używamy tagu &lt;html&gt;, który zawiera dwie główne sekcje: &lt;head&gt; i &lt;body&gt;. Sekcja &lt;head&gt; zawiera metadane, takie jak tytuł strony i odwołania do arkuszy stylów CSS. Z kolei &lt;body&gt; przechowuje treść, którą widzi użytkownik, np. nagłówki, akapity, listy, obrazy i formularze. Dobre zrozumienie tej struktury jest kluczowe, aby skutecznie tworzyć strony internetowe i dbać o ich dostępność oraz semantykę.','2024-11-18 10:30:00', true, 2, 1),
    ('Formularze HTML: Wprowadzenie','Formularze w HTML pozwalają na zbieranie danych od użytkowników, co jest kluczowe w aplikacjach internetowych. Formularze są używane na stronach rejestracyjnych, logowaniach, ankietach i wielu innych. Podstawowym tagiem jest &lt;form&gt;, który otacza wszystkie elementy formularza. Wewnątrz formularza możemy używać różnych tagów, takich jak &lt;input&gt;, &lt;textarea&gt;, &lt;select&gt; czy &lt;button&gt;. Dzięki formularzom użytkownicy mogą wprowadzać dane, które są następnie przesyłane na serwer. Warto znać atrybuty takie jak action i method, które określają sposób przesyłania danych oraz adres, na który mają zostać wysłane.', '2024-11-17 14:45:00', true, 3, 1),
    ('Tworzenie linków w HTML', 'Linki są nieodłącznym elementem internetu i jednym z najważniejszych składników HTML. Za pomocą tagu &lt;a&gt; możemy tworzyć odnośniki do innych stron internetowych, sekcji na tej samej stronie lub nawet do plików do pobrania. Atrybut href jest odpowiedzialny za określenie docelowego adresu URL. Linki mogą mieć różne style, np. mogą być podkreślone, zmieniać kolor po najechaniu myszką czy działać jako przyciski. Warto również pamiętać o atrybucie target, który pozwala określić, w jakim oknie lub karcie przeglądarki ma otworzyć się link. Linki są również niezbędne w zapewnieniu dostępności strony, ponieważ umożliwiają nawigację i interakcję z zawartością strony.', '2024-11-16 09:15:00', true, 4, 1),
    ('Rola semantycznych tagów HTML5','Semantyczne tagi HTML, takie jak &lt;header&gt;, &lt;article&gt;, &lt;section&gt;, &lt;footer&gt;, &lt;nav&gt; i inne, mają kluczowe znaczenie zarówno z perspektywy dostępności, jak i SEO. Używanie semantycznych tagów pozwala nie tylko na lepsze uporządkowanie treści na stronie, ale także umożliwia lepsze indeksowanie strony przez wyszukiwarki internetowe. Na przykład, &lt;header&gt; zawiera nagłówki strony, a &lt;footer&gt; informacje o autorze czy polityce prywatności. Dzięki tym tagom łatwiej jest zrozumieć, jaka część strony odpowiada za jaką funkcjonalność. Semantyczne tagi są również korzystne dla osób korzystających z technologii asystujących, takich jak czytniki ekranowe, ponieważ ułatwiają orientację na stronie.', '2024-11-15 17:30:00', true, 5, 1),
    ('Zaawansowane techniki z HTML5', 'HTML5, wprowadzony jako standard, dodał szereg nowych funkcji, które ułatwiają tworzenie interaktywnych i multimedialnych stron internetowych. Dzięki tagom takim jak &lt;video&gt;, &lt;audio&gt;, &lt;canvas&gt; czy &lt;svg&gt; możliwe jest osadzanie multimediów i grafiki wektorowej bez potrzeby używania wtyczek. HTML5 wprowadza również wsparcie dla lokalnego przechowywania danych i obsługi geolokalizacji, co otwiera nowe możliwości dla aplikacji webowych. Dzięki tym technologiom strony stają się bardziej dynamiczne i interaktywne, a programiści zyskują nowe narzędzia do tworzenia nowoczesnych aplikacji internetowych.', '2024-11-14 12:00:00', true, 1, 1),
    ('Jak poprawnie używać tabel w HTML?', 'Tabele w HTML służą do prezentowania danych w formie wierszy i kolumn. Chociaż mogą być używane do układania treści, to należy pamiętać, że ich głównym zadaniem jest prezentacja informacji. Tabela tworzona jest za pomocą tagu &lt;table&gt;, a jej wiersze to tagi &lt;tr&gt;, które zawierają komórki danych z tagiem &lt;td&gt;. Istnieją również nagłówki tabeli, które tworzymy za pomocą tagu &lt;th&gt;. Ważne jest, aby unikać używania tabel do układu strony, ponieważ nowoczesne techniki CSS, takie jak Flexbox i Grid, pozwalają na bardziej elastyczne i responsywne podejście do układu strony.', '2024-11-13 16:00:00', true, 2, 1),
    ('Co to jest atrybut alt w HTML?', 'Atrybut alt jest używany w tagu &lt;img&gt; i jest kluczowy z perspektywy dostępności oraz SEO. Atrybut alt opisuje obraz, który nie może być załadowany lub wyświetlony. Jest to również ważne dla osób korzystających z czytników ekranu, ponieważ alt dostarcza opisu obrazu. Dobre praktyki wskazują, że tekst w atrybucie alt powinien być zwięzły, ale jednocześnie dokładny, opisując, co znajduje się na obrazie. Ponadto, dobrze napisany atrybut alt pomaga poprawić wyniki SEO strony, ponieważ wyszukiwarki używają tych informacji do lepszego indeksowania treści wizualnych.', '2024-11-12 11:30:00', true, 3, 1),

    # CSS
    ('Wprowadzenie do CSS', 'CSS, czyli Cascading Style Sheets, to technologia odpowiedzialna za stylizowanie wyglądu stron internetowych. Dzięki CSS możemy zmieniać kolory tła, czcionki, układy, marginesy, obramowania i wiele innych elementów strony. Składa się z selektorów, które wybierają elementy HTML, oraz deklaracji, które określają styl dla tych elementów. Istnieją różne metody stosowania CSS na stronie, w tym zewnętrzne pliki CSS, style w nagłówku dokumentu lub inline. Zrozumienie CSS jest niezbędne, aby tworzyć estetyczne, responsywne i funkcjonalne strony internetowe.', '2024-11-19 08:30:00', true, 1, 2),
    ('CSS Grid: Podstawy tworzenia układów', 'CSS Grid to system, który pozwala na tworzenie złożonych układów stron za pomocą siatek. Dzięki CSS Grid możemy definiować kolumny i wiersze, a następnie umieszczać elementy w odpowiednich komórkach siatki. Zaletą CSS Grid jest to, że pozwala na precyzyjne ustawienie elementów na stronie, co sprawia, że projektowanie stron staje się bardziej elastyczne. Siatka może być dynamiczna, tzn. może dostosowywać się do różnych rozmiarów ekranu, co jest szczególnie ważne w kontekście responsywności stron internetowych. Dzięki CSS Grid, projektanci mogą tworzyć nowoczesne i dobrze wyglądające układy stron.', '2024-11-18 10:00:00', true, 2, 2),
    ('Flexbox: Elastyczny układ CSS', 'Flexbox to jedno z narzędzi CSS, które pozwala na elastyczne rozmieszczanie elementów na stronie. Dzięki Flexbox możemy łatwo ustawić elementy w jednym wierszu lub kolumnie, zmieniając ich rozmiar i porządek. Flexbox jest szczególnie użyteczny w tworzeniu responsywnych stron internetowych, ponieważ pozwala na automatyczne dostosowywanie się do różnych rozmiarów ekranu. Możemy także określić, jak elementy mają się rozmieszczać w przestrzeni, zarówno w poziomie, jak i w pionie. W przeciwieństwie do tradycyjnych układów opartych na float, Flexbox daje większą kontrolę i jest prostszy w implementacji.', '2024-11-17 09:30:00', true, 3, 2),
    ('Zaawansowane selektory CSS', 'Selekcja elementów w CSS jest kluczowym elementem stylizowania stron. Dzięki selektorom możemy wybrać konkretne elementy, klasy lub identyfikatory do stylizacji. CSS oferuje również zaawansowane selektory, takie jak selektory potomków, rodziców, pseudo-klasy i pseudo-elementy. Pseudo-klasy, takie jak :hover, :active, :focus, pozwalają na stosowanie stylów w zależności od stanu elementu. Pseudo-elementy, takie jak ::before i ::after, pozwalają na dodawanie treści przed lub po danym elemencie, co daje ogromne możliwości w stylizowaniu. Dzięki zaawansowanym selektorom CSS, możemy precyzyjnie kontrolować wygląd elementów na stronie.', '2024-11-16 08:00:00', true, 4, 2),
    ('Wprowadzenie do animacji CSS', 'Animacje CSS pozwalają na tworzenie dynamicznych efektów na stronie bez użycia JavaScript. Dzięki animacjom możemy zmieniać style elementów w czasie, co pozwala na tworzenie atrakcyjnych przejść i efektów wizualnych. CSS oferuje dwie główne metody animacji: transitions i keyframes. Transitions pozwalają na płynne przejścia między stanami elementów, natomiast keyframes pozwalają na bardziej złożone animacje, w których definiujemy szczegółowo zmiany stylów w różnych punktach czasu. Animacje CSS poprawiają wrażenia użytkownika i sprawiają, że strona wygląda bardziej interaktywnie i nowocześnie.', '2024-11-14 09:30:00', true, 1, 2),
    ('Media Queries w CSS: Responsywność', 'Media Queries to technika w CSS, która pozwala na dostosowanie stylów do różnych urządzeń i rozmiarów ekranów. Dzięki nim możemy tworzyć responsywne strony internetowe, które będą dobrze wyglądać zarówno na komputerach, tabletach, jak i telefonach. Media Queries pozwalają na stosowanie różnych reguł CSS w zależności od szerokości ekranu, orientacji urządzenia czy jego rozdzielczości. Przykład użycia: @media (max-width: 768px) { /* style dla urządzeń o szerokości ekranu mniejszej niż 768px */ }. Media Queries są niezbędne w nowoczesnym web designie, umożliwiając tworzenie stron, które są przyjazne użytkownikom na różnych urządzeniach. Queries to kluczowe narzędzie dla projektantów stron responsywnych. Dzięki nim można dostosować wygląd strony do różnych rozdzielczości ekranów.', '2024-11-16 14:00:00', true, 4, 2),
    ('SASS: Rozszerzenie CSS', 'SASS (Syntactically Awesome Stylesheets) to popularny preprocesor CSS, który umożliwia pisanie bardziej zaawansowanych arkuszy stylów w CSS. SASS wprowadza zmienne, zagnieżdżanie selektorów, mixiny, funkcje oraz inne narzędzia, które ułatwiają organizowanie i utrzymywanie dużych projektów CSS. Dzięki zmiennym możemy przechowywać wartości, takie jak kolory czy rozmiary, które później wykorzystywane są w całym projekcie. Zagnieżdżanie selektorów pozwala na tworzenie bardziej hierarchicznych i czytelnych arkuszy stylów, a mixiny umożliwiają wielokrotne używanie tej samej grupy właściwości. SASS ułatwia zarządzanie stylem i zwiększa efektywność pracy nad większymi projektami CSS.', '2024-11-15 13:30:00', true, 5, 2),

    # JavaScript
    ('Wprowadzenie do JavaScript', 'JavaScript to język programowania wykorzystywany głównie do tworzenia interaktywnych aplikacji webowych. Został stworzony z myślą o umożliwieniu manipulowania treścią stron internetowych w czasie rzeczywistym. JavaScript jest językiem skryptowym, który działa po stronie klienta, co oznacza, że jego kod jest wykonywany przez przeglądarkę użytkownika. Dzięki JavaScriptowi można dynamicznie zmieniać zawartość stron, walidować formularze, reagować na zdarzenia (np. kliknięcia) i wiele więcej. Język jest także wykorzystywany po stronie serwera, dzięki takim narzędziom jak Node.js. JavaScript stał się fundamentem nowoczesnego web developmentu, pozwalając na tworzenie interaktywnych i responsywnych aplikacji.', '2024-11-09 09:00:00', true, 1, 3),
    ('Asynchroniczność w JavaScript', 'JavaScript jest językiem, który wspiera asynchroniczność, co oznacza, że operacje mogą być wykonywane niezależnie od siebie, bez blokowania reszty programu. Najczęściej używanymi mechanizmami do pracy z asynchronicznością są callbacki, promisy oraz async/await. Callbacki to funkcje, które są przekazywane jako argumenty do innych funkcji i wywoływane, gdy operacja asynchroniczna jest zakończona. Promisy to obiekty, które reprezentują wynik operacji asynchronicznej, które mogą zakończyć się sukcesem lub błędem. Async/await to syntaktyczny cukierek, który umożliwia pisanie asynchronicznego kodu w sposób synchroniczny, co zwiększa jego czytelność.', '2024-11-16 10:30:00', true, 4, 3),
    ('Obiekty w JavaScript', 'Obiekty w JavaScript to kolejne fundamenty tego języka. Są to zbiory par klucz-wartość, które pozwalają na przechowywanie danych w zorganizowany sposób. Obiekt może przechowywać różne właściwości i metody, które mogą być wywoływane na obiekcie. Tworzenie obiektów w JavaScript jest bardzo elastyczne - można je tworzyć za pomocą literałów obiektów, konstruktorów lub za pomocą klas. Obiekty stanowią podstawę wielu struktur danych i często są używane do reprezentowania bardziej złożonych bytów w aplikacjach, takich jak użytkownicy, produkty czy zamówienia.', '2024-11-14 15:30:00', true, 2, 3),
    ('DOM i manipulowanie elementami w JavaScript', 'DOM (Document Object Model) to interfejs, który reprezentuje strukturę dokumentu HTML jako drzewa obiektów. JavaScript umożliwia manipulowanie elementami strony internetowej za pomocą DOM, co pozwala na dynamiczną zmianę zawartości strony bez konieczności jej przeładowania. Można dodawać, usuwać, modyfikować elementy HTML, a także reagować na zdarzenia, takie jak kliknięcia, przesunięcia czy wprowadzanie danych. Najczęściej wykorzystywane metody do pracy z DOM to "getElementById", "getElementsByClassName", "querySelector", "createElement" oraz "appendChild". Dzięki tym funkcjom można tworzyć dynamiczne strony i aplikacje webowe.', '2024-11-13 11:00:00', true, 1, 3),
    ('Wprowadzenie do jQuery', 'jQuery to popularna biblioteka JavaScript, która ułatwia manipulowanie elementami DOM, obsługę zdarzeń, animacje oraz wykonywanie zapytań AJAX. Jednym z głównych atutów jQuery jest jego prostota – biblioteka umożliwia wykonywanie skomplikowanych operacji w kilku linijkach kodu, co w tradycyjnym JavaScript mogłoby wymagać większej ilości kodu. Dzięki jQuery łatwo jest tworzyć interaktywne strony internetowe, a także dostosowywać je do różnych przeglądarek. Chociaż jQuery było kiedyś fundamentem w rozwoju aplikacji webowych, dziś jest mniej popularne, gdyż nowoczesne frameworki, takie jak React czy Angular, oferują większą elastyczność i skalowalność.', '2024-11-19 14:30:00', true, 3, 3),
    ('React - Nowoczesny framework do budowy interfejsów', 'React to biblioteka JavaScript do tworzenia interfejsów użytkownika, stworzona przez Facebook. Jego głównym celem jest umożliwienie tworzenia dynamicznych i wydajnych aplikacji webowych poprzez komponenty. React wprowadza koncepcję wirtualnego DOM, co sprawia, że zmiany w interfejsie są wykonywane w sposób optymalny, minimalizując liczbę operacji na prawdziwym DOM. React pozwala na tworzenie aplikacji, które są łatwe do rozbudowy i utrzymania dzięki modularności i ponownemu wykorzystywaniu komponentów. React jest bardzo popularny w tworzeniu aplikacji jednostronicowych (SPA), oferując dużą wydajność i bogaty ekosystem narzędzi.', '2024-11-18 12:00:00', true, 3, 3),
    ('Angular - Framework do budowy dynamicznych aplikacji webowych', 'Angular to framework JavaScript, który umożliwia budowanie aplikacji webowych opartej na wzorcu MVC (Model-View-Controller). Jest to rozbudowane narzędzie do tworzenia dynamicznych, skalowalnych aplikacji z użyciem TypeScriptu. Angular oferuje bogaty zestaw funkcji, takich jak dwukierunkowe powiązanie danych, routowanie, formularze oraz możliwość integracji z różnymi API. Jednym z kluczowych atutów Angulara jest jego zdolność do zarządzania złożonymi aplikacjami i zapewnienie ich wysokiej wydajności. Angular jest preferowany do tworzenia większych aplikacji, które wymagają zaawansowanej struktury i organizacji kodu.', '2024-11-17 09:30:00', true, 3, 3),
    ('Vue.js - Lekki i elastyczny framework JavaScript', 'Vue.js to progresywny framework JavaScript, który łączy w sobie najlepsze cechy Angulara i Reacta, ale w bardziej lekkiej i elastycznej formie. Vue.js jest łatwy do integracji z istniejącymi projektami, co sprawia, że jest dobrym wyborem zarówno dla małych aplikacji, jak i dużych systemów. Framework ten oferuje prostą składnię, doskonałą dokumentację oraz mechanizmy takie jak dwukierunkowe wiązanie danych, komponenty, routing i zarządzanie stanem aplikacji. Vue jest szczególnie cenione za jego łatwość nauki, wydajność i możliwość stopniowego wdrażania w projekcie, co czyni go idealnym wyborem dla początkujących oraz zaawansowanych programistów.', '2024-11-16 11:00:00', true, 3, 3),

    # TypeScript
    ('Wprowadzenie do TypeScriptu', 'TypeScript to język programowania, który rozszerza JavaScript o statyczne typowanie. Umożliwia to wcześniejsze wykrywanie błędów w kodzie, co sprawia, że kod jest bardziej bezpieczny i łatwiejszy do utrzymania. TypeScript pozwala na definiowanie typów dla zmiennych, funkcji i obiektów, co pomaga w utrzymaniu większych projektów. TypeScript jest kompilowany do czystego JavaScriptu, dzięki czemu może być uruchamiany w każdej przeglądarce oraz na serwerach Node.js. Dzięki swojej kompatybilności z JavaScript, TypeScript jest coraz częściej wykorzystywany w dużych aplikacjach webowych.', '2024-11-19 15:00:00', true, 1, 4),
    ('Dlaczego warto używać TypeScriptu?', 'TypeScript jest szczególnie przydatny w dużych aplikacjach, gdzie kontrolowanie typów może zapobiec wielu błędom. Dzięki wczesnemu wykrywaniu błędów i silniejszemu typowaniu, programiści mogą uniknąć problemów związanych z niezgodnością typów, które są częste w JavaScript. TypeScript wspiera również obiektowo-orientowane podejście do programowania, umożliwiając korzystanie z klas, interfejsów, dziedziczenia i innych mechanizmów. Dodatkowo, TypeScript pozwala na łatwiejszą współpracę w zespołach, ponieważ kod jest bardziej czytelny, a intellisense w edytorach kodu jest bardziej precyzyjny.', '2024-11-18 14:00:00', true, 2, 4),
    ('TypeScript a JavaScript - Różnice i korzyści', 'Chociaż TypeScript jest nadzbiorem JavaScriptu, różni się od niego pod względem składni i funkcjonalności. Główną różnicą jest wprowadzenie typów, które w JavaScript są dynamiczne, a w TypeScript statyczne. Dzięki typowaniu, TypeScript pomaga zapobiegać błędom związanym z nieodpowiednimi typami danych, co jest szczególnie ważne w dużych projektach. TypeScript wspiera również nowoczesne funkcje JavaScriptu, takie jak async/await, oraz pozwala na korzystanie z nowych funkcji ECMAScript zanim staną się one szeroko wspierane. Co ważne, TypeScript jest kompilowany do czystego JavaScriptu, więc może być używany w każdym środowisku, które obsługuje JavaScript.', '2024-11-17 13:00:00', true, 2, 4),
    ('Podstawowe typy danych w TypeScript', 'TypeScript wprowadza kilka podstawowych typów danych, które pozwalają na precyzyjne określenie rodzaju danych. Do najczęściej używanych należą: string, number, boolean, oraz bardziej zaawansowane jak arrays, tuples czy any. Dzięki tym typom, programiści mogą określić, jakie dane mają być przechowywane w zmiennych, co zapobiega błędom podczas wykonywania aplikacji. Ponadto TypeScript wspiera typy wyliczeniowe (enums) oraz umożliwia tworzenie własnych typów za pomocą interfejsów i aliasów, co pozwala na pełną kontrolę nad strukturą danych w aplikacji.', '2024-11-16 10:30:00', true, 2, 4),
    ('Zastosowanie interfejsów w TypeScript', 'Interfejsy w TypeScript pozwalają na definiowanie kontraktów dla obiektów. Dzięki nim można określić, jakie właściwości i metody powinny znajdować się w obiektach, co zwiększa czytelność i niezawodność kodu. Interfejsy są szczególnie przydatne, gdy pracujemy z dużymi aplikacjami, w których wiele obiektów ma podobną strukturę. TypeScript pozwala na implementację interfejsów w klasach, co pozwala na tworzenie bardziej elastycznych i modułowych aplikacji. Interfejsy umożliwiają także tworzenie bardziej zaawansowanych typów, takich jak funkcje czy tablice.', '2024-11-15 16:00:00', true, 4, 4),

    # Python
    ('Wprowadzenie do Pythona', 'Python jest jednym z najbardziej przyjaznych języków do nauki, głównie dzięki swojej prostej składni. Zamiast używać nawiasów klamrowych do definiowania bloków kodu, Python korzysta z wcięć, co sprawia, że kod jest bardziej przejrzysty. Zmienna w Pythonie nie wymaga wcześniejszego deklarowania typu, ponieważ jest to język dynamicznie typowany. Python pozwala także na łatwe operowanie na listach, słownikach, krotkach i zbiorach, co czyni go elastycznym i wszechstronnym językiem programowania. Dzięki prostocie składni, Python jest świetnym wyborem dla osób, które zaczynają swoją przygodę z programowaniem. Jego bogaty ekosystem bibliotek i frameworków, takich jak Django, Flask czy TensorFlow, sprawia, że Python jest jednym z najczęściej wybieranych języków w branży IT', '2024-11-09 12:00:00', true, 1, 7),
    ('Zastosowanie Python w nauce i analizie danych', 'Python stał się jednym z najważniejszych języków w dziedzinie analizy danych i uczenia maszynowego, dzięki bibliotekam takim jak NumPy, Pandas, SciPy i Matplotlib. NumPy oferuje narzędzia do obliczeń numerycznych, Pandas jest wykorzystywane do pracy z danymi tabelarycznymi, a SciPy dostarcza narzędzi do bardziej zaawansowanych obliczeń matematycznych. Dzięki tym bibliotekom Python jest doskonałym wyborem dla osób, które pracują w obszarze analizy danych, statystyki, a także sztucznej inteligencji. Python jest także wykorzystywany w badaniach naukowych, gdzie umożliwia szybkie i efektywne przeprowadzanie skomplikowanych analiz.', '2024-11-22 09:30:00', true, 3, 7),
    ('Dlaczego warto używać Pythona w backendzie?', 'Python jest jednym z najczęściej wybieranych języków do tworzenia aplikacji backendowych dzięki swojej prostocie, szybkości rozwoju i ogromnej liczbie dostępnych bibliotek. Frameworki takie jak Django i Flask umożliwiają szybkie budowanie solidnych i skalowalnych aplikacji webowych. Python jest również wydajny w zarządzaniu bazami danych, obsłudze zapytań HTTP oraz integracji z innymi systemami. Dzięki dużej społeczności, Python oferuje wsparcie dla najnowszych technologii, co czyni go atrakcyjnym wyborem dla twórców aplikacji backendowych.', '2024-11-18 14:30:00', true, 2, 7),
    ('Wprowadzenie do Pythona w backendzie', 'Python jest jednym z najpopularniejszych języków programowania do tworzenia aplikacji backendowych. Dzięki swojej prostocie i ogromnej liczbie dostępnych bibliotek, jest chętnie wybierany do budowy rozwiązań serwerowych. Frameworki takie jak Django czy Flask pozwalają szybko tworzyć aplikacje webowe z pełnym backendem. Django zapewnia gotowy zestaw funkcjonalności, takich jak system logowania, ORM do pracy z bazami danych, a także mechanizm routingu. Flask, z kolei, to mikroframework, który daje programiście pełną kontrolę nad tym, jak aplikacja będzie wyglądała i działała. Python w backendzie to świetna opcja dla szybkiego prototypowania i rozwoju aplikacji.', '2024-11-19 09:00:00', true, 1, 7),
    ('Django vs Flask - Kiedy wybrać który framework?', 'Zarówno Django, jak i Flask są niezwykle popularnymi frameworkami w Pythonie, ale służą różnym celom. Django to framework o pełnym stosie, co oznacza, że oferuje gotowe rozwiązania dla większości problemów, które mogą wystąpić podczas budowy aplikacji webowej. Flask jest z kolei bardziej minimalistyczny i daje większą elastyczność w tworzeniu aplikacji, ale wymaga od programisty więcej pracy przy implementowaniu dodatkowych funkcjonalności. Wybór pomiędzy nimi zależy od specyfiki projektu: jeśli zależy nam na szybszym rozwoju i mamy standardowe potrzeby, Django będzie odpowiednie. Jeśli natomiast projekt wymaga większej elastyczności, lepszym wyborem będzie Flask.', '2024-11-20 10:30:00', true, 2, 7),
    ('Praca z bazami danych w Pythonie', 'Python świetnie współpracuje z wieloma systemami baz danych, takimi jak MySQL, PostgreSQL, MongoDB czy SQLite. W Django i Flask mamy do dyspozycji ORM (Object-Relational Mapping), który umożliwia mapowanie obiektów Pythonowych na tabele w bazie danych. Django posiada wbudowane ORM, które pozwala na łatwą interakcję z bazą danych za pomocą zapytań w postaci obiektów. Flask, chociaż jest minimalistyczny, pozwala na integrację z SQLAlchemy, co daje podobne możliwości. Dzięki tym narzędziom Python jest idealnym rozwiązaniem do tworzenia aplikacji backendowych, które wymagają solidnego i wydajnego zarządzania danymi.', '2024-11-19 14:45:00', true, 1, 7),
    ('Integracja z API w Pythonie', 'Python oferuje wiele bibliotek do integracji z zewnętrznymi API, co jest kluczowym elementem w budowie nowoczesnych aplikacji backendowych. Jedną z najpopularniejszych bibliotek do tego celu jest "requests", która umożliwia wykonywanie zapytań HTTP i obsługę odpowiedzi. Dzięki "requests" programista może łatwo połączyć się z API, pobrać dane, a następnie przetworzyć je w aplikacji. Ponadto, Python doskonale współpracuje z systemami kolejkowymi, co umożliwia obsługę dużych ilości zapytań API w sposób asynchroniczny. Dzięki temu, Python jest idealnym językiem do tworzenia aplikacji backendowych, które muszą współpracować z wieloma zewnętrznymi serwisami.', '2024-11-21 11:40:00', true, 2, 7),
    ('Zalety i wady Pythona w rozwoju aplikacji backendowych', 'Python ma wiele zalet jako język do budowy aplikacji backendowych. Jego czytelna składnia i szybka nauka sprawiają, że jest to świetny wybór dla programistów na każdym poziomie zaawansowania. Dodatkowo, Python posiada ogromną liczbę bibliotek, co przyspiesza proces tworzenia aplikacji. Jednakże, Python ma swoje ograniczenia – w porównaniu do innych języków, takich jak Java czy C++, może być nieco wolniejszy w przetwarzaniu dużych ilości danych. Mimo to, dzięki szerokiemu wsparciu dla rozwoju aplikacji webowych i łatwości integracji z innymi systemami, Python pozostaje jednym z najczęściej wybieranych języków backendowych.', '2024-11-15 12:00:00', true, 1, 7),

    # C#
    ('Wprowadzenie do C# – Język o wszechstronnych możliwościach', 'C# to wszechstronny język programowania stworzony przez Microsoft, który jest szeroko wykorzystywany w aplikacjach desktopowych, webowych oraz mobilnych. Dzięki swojej prostocie i elastyczności, C# jest doskonałym wyborem zarówno dla początkujących, jak i zaawansowanych programistów. Język oferuje silne wsparcie dla programowania obiektowego, funkcjonalnego oraz współbieżnego. C# jest także ściśle zintegrowany z platformą .NET, co zapewnia dostęp do bogatego ekosystemu narzędzi i bibliotek, ułatwiając tworzenie aplikacji o dużej wydajności.', '2024-11-19 17:00:00', true, 1, 8),
    ('C# w tworzeniu aplikacji webowych', 'C# jest jednym z głównych języków wykorzystywanych w tworzeniu aplikacji webowych, zwłaszcza w połączeniu z platformą ASP.NET. Dzięki ASP.NET, programiści mogą tworzyć dynamiczne aplikacje webowe, które są skalowalne, bezpieczne i wydajne. C# i ASP.NET wspierają różne modele programowania, takie jak MVC (Model-View-Controller), co pomaga w organizowaniu kodu aplikacji. Ponadto, dzięki wbudowanej obsłudze baz danych i middleware, proces tworzenia aplikacji webowych jest znacznie uproszczony, a czas potrzebny na wdrożenie produktu jest krótszy.', '2024-11-18 14:30:00', true, 2, 8),
    ('Zalety i wady używania C# w backendzie', 'C# to popularny język wykorzystywany w backendzie aplikacji webowych, szczególnie w połączeniu z frameworkiem ASP.NET. Jego główną zaletą jest łatwość w integracji z platformą Microsoftu, co czyni go idealnym wyborem dla aplikacji opartych na systemach Windows. C# zapewnia wysoką wydajność, a jego zintegrowane narzędzia ułatwiają rozwój aplikacji backendowych. Jednakże, C# jest często postrzegany jako mniej elastyczny w porównaniu do innych języków takich jak Python czy JavaScript, szczególnie w środowisku, które nie jest zdominowane przez technologie Microsoft.', '2024-11-17 10:00:00', true, 3, 8),
    ('C# i .NET Core – Nowoczesne podejście do tworzenia aplikacji backendowych', 'C# w połączeniu z .NET Core to potężne narzędzie do tworzenia aplikacji backendowych. .NET Core to wieloplatformowe środowisko uruchomieniowe, które umożliwia tworzenie aplikacji działających na różnych systemach operacyjnych, takich jak Windows, Linux czy macOS. Dzięki .NET Core programiści mogą tworzyć aplikacje o dużej wydajności, które mogą być łatwo skalowane i utrzymywane. C# w tym środowisku oferuje wszystkie korzyści związane z programowaniem obiektowym, jednocześnie zapewniając wsparcie dla nowoczesnych technologii, takich jak mikroserwisy.', '2024-11-14 11:30:00', true, 1, 8),

    # Ruby
    ('Wprowadzenie do Ruby – Język programowania o prostocie i mocy', 'Ruby to dynamiczny język programowania, który zyskał popularność dzięki swojej prostocie i eleganckiej składni. Jego celem jest umożliwienie twórcom pisania kodu, który jest zarówno czytelny, jak i wydajny. Ruby znajduje zastosowanie w wielu dziedzinach programowania, ale jego prawdziwa siła objawia się w tworzeniu aplikacji backendowych, szczególnie w połączeniu z frameworkiem Ruby on Rails. Język oferuje bogaty zestaw bibliotek i narzędzi, które przyspieszają rozwój aplikacji webowych, a także wsparcie dla wielu popularnych baz danych.', '2024-11-19 17:00:00', true, 1, 9),
    ('Ruby on Rails – Szybki rozwój aplikacji webowych', 'Ruby on Rails to jeden z najpopularniejszych frameworków webowych, który opiera się na języku Ruby. Rails umożliwia szybkie tworzenie aplikacji webowych, korzystając z zestawu wbudowanych narzędzi, które automatyzują wiele zadań. Dzięki konwencjom nad konfiguracją, Rails przyspiesza proces budowania aplikacji i jest szczególnie ceniony za możliwość szybkiego prototypowania. Jego struktura MVC (Model-View-Controller) organizuje kod w sposób, który pozwala na łatwą rozbudowę i utrzymanie aplikacji. Rails to wybór wielu startupów oraz dużych firm, które potrzebują szybko wprowadzać zmiany.', '2024-11-18 14:30:00', true, 2, 9),
    ('Dlaczego Ruby to dobry wybór na backend?', 'Ruby jest jednym z najlepszych języków programowania, jeśli chodzi o szybki rozwój aplikacji backendowych. Jego składnia jest intuicyjna i prosta, co pozwala programistom na tworzenie czystego i łatwego do utrzymania kodu. W połączeniu z Ruby on Rails, Ruby umożliwia szybkie tworzenie aplikacji webowych, które są skalowalne i łatwe w zarządzaniu. Framework Ruby on Rails zapewnia szereg wbudowanych funkcji, takich jak zarządzanie bazami danych, routing i autoryzacja, co pozwala skupić się na logice biznesowej, zamiast na konfiguracji systemu.', '2024-11-17 10:00:00', true, 3, 9),
    ('Jak Ruby on Rails wspiera rozwój aplikacji webowych?', 'Ruby on Rails to framework, który znacząco skraca czas potrzebny na rozwój aplikacji webowych. Dzięki automatyzacji wielu procesów, takich jak generowanie szkieletu aplikacji, zarządzanie bazą danych i obsługa zapytań HTTP, Rails pozwala programistom skoncentrować się na logice aplikacji. Dzięki swoim konwencjom, Rails zapewnia wysoki poziom bezpieczeństwa, minimalizując ryzyko błędów w aplikacjach. Jest to idealne rozwiązanie dla twórców, którzy chcą szybko wdrożyć swoje pomysły i budować aplikacje o dużym potencjale rozwoju.', '2024-11-16 13:30:00', true, 4, 9),
    ('Zalety i wady Ruby w backendzie', 'Ruby, a szczególnie framework Ruby on Rails, jest popularnym wyborem wśród twórców aplikacji webowych. Jego zaletą jest szybka nauka, elegancka składnia oraz ogromna liczba gotowych rozwiązań w postaci bibliotek i gemów. Rails automatyzuje wiele zadań, co przyspiesza rozwój aplikacji. Jednak Ruby ma również swoje wady, w tym słabszą wydajność w porównaniu do innych języków takich jak Java czy C#. Pomimo tego, Ruby jest nadal jednym z najczęściej wybieranych języków w startupach i małych firmach, które potrzebują szybko zbudować działający produkt.', '2024-11-15 12:00:00', true, 5, 9),
    ('Wykorzystanie Ruby w tworzeniu API', 'Ruby, z frameworkiem Ruby on Rails, jest świetnym wyborem do tworzenia aplikacji webowych oraz API. Rails oferuje wbudowane narzędzia do szybkiego tworzenia endpointów i zarządzania danymi, co czyni go idealnym rozwiązaniem dla tworzenia RESTful API. Ponadto, dzięki bibliotekom takim jak Grape czy Sinatra, Ruby może być używane do tworzenia lżejszych API, które są szybkie i wydajne. W połączeniu z bazami danych, takimi jak PostgreSQL, Ruby pozwala na efektywne zarządzanie danymi i obsługę zapytań, co jest kluczowe w aplikacjach backendowych.', '2024-11-14 11:30:00', true, 1, 9),
    ('Praca z bazami danych w Ruby on Rails', 'Ruby on Rails ma doskonałą obsługę baz danych, co czyni go potężnym narzędziem do tworzenia aplikacji backendowych. Framework ten wykorzystuje ActiveRecord, który jest ORM (Object-Relational Mapping), pozwalając na łatwe mapowanie obiektów Ruby na tabele w bazie danych. Dzięki ActiveRecord, operacje na bazie danych są prostsze i bardziej intuicyjne, co skraca czas potrzebny na tworzenie aplikacji. Rails obsługuje wiele baz danych, takich jak PostgreSQL, MySQL, SQLite, co czyni go elastycznym rozwiązaniem do tworzenia aplikacji webowych z backendem opartym na bazach danych.', '2024-11-13 10:00:00', true, 2, 9),

    # Assembler
    ('Wprowadzenie do Asemblera – Język niskopoziomowy', 'Asembler to język programowania niskiego poziomu, który jest bezpośrednio związany z architekturą procesora. Jego składnia jest bliska kodowi maszynowemu, co pozwala na bardzo precyzyjne kontrolowanie działania programu. Programowanie w Asemblerze jest trudniejsze niż w językach wysokiego poziomu, ale daje programiście pełną kontrolę nad sprzętem. Asembler jest wykorzystywany w zadaniach, które wymagają bezpośredniej interakcji z procesorem, takich jak pisanie sterowników, oprogramowania systemowego czy optymalizacja wydajności.', '2024-11-19 10:30:00', true, 1, 10),
    ('Asembler w programowaniu systemów wbudowanych', 'Język Asembler jest szeroko stosowany w programowaniu systemów wbudowanych, gdzie liczy się każda jednostka pamięci i wydajności. W systemach wbudowanych, takich jak urządzenia IoT, mikrokontrolery czy sprzęt medyczny, Asembler pozwala na tworzenie aplikacji o minimalnym zużyciu zasobów. Dzięki pełnej kontroli nad sprzętem, programiści mogą optymalizować działanie systemów, co jest kluczowe w przypadku urządzeń o ograniczonej mocy obliczeniowej i pamięci. Asembler jest także wykorzystywany w tworzeniu niskopoziomowych sterowników i oprogramowania obsługującego sprzęt.', '2024-11-18 15:00:00', true, 2, 10),
    ('Jak Asembler współpracuje z językami wysokiego poziomu?', 'Choć Asembler jest językiem niskopoziomowym, często współpracuje z językami wysokiego poziomu, takimi jak C czy C++, szczególnie w systemach wbudowanych. Część krytyczna aplikacji może być napisana w Asemblerze, podczas gdy reszta programu jest realizowana w języku wyższego poziomu. Tego typu podejście pozwala na uzyskanie maksymalnej wydajności tam, gdzie jest to konieczne, a jednocześnie zachowanie czytelności i łatwości utrzymania kodu w pozostałych częściach aplikacji. Dzięki temu, Asembler i języki wyższego poziomu mogą działać synergicznie, zapewniając zarówno wydajność, jak i elastyczność.', '2024-11-15 11:30:00', true, 2, 10),
    ('Asembler w tworzeniu oprogramowania systemowego', 'Asembler jest wykorzystywany do tworzenia oprogramowania systemowego, takiego jak jądra systemów operacyjnych, programy rozruchowe (bootloadery) i inne elementy niskopoziomowe. Dzięki bezpośredniej kontroli nad procesorem i pamięcią, programiści mogą pisać oprogramowanie, które jest maksymalnie zoptymalizowane i wydajne. Język Asembler pozwala również na pełne wykorzystanie funkcji procesora, co jest szczególnie przydatne w systemach o ograniczonych zasobach, takich jak mikrokontrolery czy urządzenia wbudowane. Asembler odgrywa kluczową rolę w tworzeniu systemów operacyjnych i innych oprogramowań systemowych.', '2024-11-14 09:30:00', true, 1, 10),

    # C
    ('Wprowadzenie do języka C – podstawy', 'Język C jest jednym z najstarszych i najczęściej używanych języków programowania niskiego poziomu. Zapewnia on bezpośrednią kontrolę nad pamięcią, co pozwala na pisanie wydajnych programów. C jest wykorzystywany głównie w systemach operacyjnych, programowaniu sterowników i systemach wbudowanych. Jego składnia jest stosunkowo prosta, ale oferuje zaawansowane funkcje, takie jak wskaźniki, które pozwalają na manipulację pamięcią. Pomimo swojej prostoty, C daje programiście pełną kontrolę nad sprzętem, co czyni go niezastąpionym w wielu dziedzinach programowania.', '2024-11-19 10:30:00', true, 1, 11),
    ('Język C w systemach wbudowanych', 'Język C jest podstawowym językiem używanym w programowaniu systemów wbudowanych, takich jak urządzenia IoT, mikrokontrolery czy sprzęt medyczny. Dzięki niskopoziomowym możliwościom, C pozwala na tworzenie aplikacji, które są szybkie i efektywne pod względem zużycia pamięci. Programowanie w C w systemach wbudowanych umożliwia pełną kontrolę nad sprzętem, co jest kluczowe w przypadku urządzeń o ograniczonej mocy obliczeniowej. C pozwala na bezpośrednią interakcję z pamięcią i procesorem, co sprawia, że jest to idealny język do pracy z mikrokontrolerami.', '2024-11-18 15:00:00', true, 2, 11),
    ('C jako język do programowania niskopoziomowego', 'Język C jest jednym z najczęściej wybieranych języków do programowania niskopoziomowego. Umożliwia on manipulację pamięcią i rejestrami procesora, co daje programiście pełną kontrolę nad działaniem aplikacji. C jest wykorzystywany w systemach operacyjnych, kompilatorach, narzędziach systemowych oraz w pisaniu sterowników. Dzięki swojej bliskości do sprzętu, C jest także podstawowym językiem w programowaniu mikrokontrolerów, pozwalającym na optymalizację kodu w celu uzyskania jak najlepszej wydajności.', '2024-11-17 13:30:00', true, 3, 11),
    ('Język C w tworzeniu oprogramowania systemowego', 'Język C odgrywa kluczową rolę w tworzeniu oprogramowania systemowego, w tym systemów operacyjnych, narzędzi systemowych oraz sterowników urządzeń. Dzięki możliwości pełnej kontroli nad pamięcią i sprzętem, C pozwala na pisanie oprogramowania, które działa szybko i efektywnie. Programowanie w C jest szczególnie popularne w tworzeniu oprogramowania niskopoziomowego, ponieważ oferuje programiście możliwość optymalizacji kodu oraz interakcji z różnymi komponentami sprzętowymi, co jest niezbędne w systemach wbudowanych i aplikacjach o krytycznych wymaganiach wydajnościowych.', '2024-11-16 12:00:00', true, 4, 11),
    ('C w programowaniu mikrokontrolerów', 'C jest szeroko stosowany w programowaniu mikrokontrolerów, ponieważ oferuje pełną kontrolę nad sprzętem oraz pozwala na pisanie wydajnego kodu. Mikrokontrolery są sercem wielu systemów wbudowanych, takich jak urządzenia IoT, automatyka przemysłowa, a także w medycynie i motoryzacji. Język C umożliwia bezpośrednią manipulację rejestrami mikrokontrolera oraz efektywne zarządzanie pamięcią, co jest niezbędne w systemach o ograniczonych zasobach. Dzięki swojej prostocie i wydajności, C jest podstawowym językiem wykorzystywanym w aplikacjach embedded.', '2024-11-15 11:30:00', true, 1, 11),

    # C++
    ('Wprowadzenie do języka C++', 'C++ jest jednym z najpotężniejszych języków programowania, który łączy cechy języków wysokiego poziomu z niskopoziomową kontrolą nad sprzętem. Język ten pozwala na programowanie obiektowe, a także umożliwia manipulację pamięcią za pomocą wskaźników, co czyni go idealnym do pisania aplikacji o dużych wymaganiach wydajnościowych. C++ jest wykorzystywany w szerokim zakresie – od aplikacji systemowych po gry komputerowe i oprogramowanie dla systemów wbudowanych. Dzięki wszechstronności i dużej mocy, C++ jest językiem, który znajduje zastosowanie w wielu dziedzinach programowania.', '2024-11-19 12:00:00', true, 4, 12),
    ('C++ w programowaniu systemów wbudowanych', 'C++ jest coraz częściej wybieranym językiem w programowaniu systemów wbudowanych, ze względu na swoją elastyczność i możliwość łączenia programowania obiektowego z niskopoziomową kontrolą nad sprzętem. Język ten umożliwia efektywne zarządzanie pamięcią, co jest kluczowe w przypadku urządzeń o ograniczonych zasobach. C++ pozwala na pisanie wydajnych aplikacji dla mikrokontrolerów, urządzeń IoT czy systemów automatyki. Dzięki możliwości wykorzystania zaawansowanych funkcji, takich jak szablony i wskaźniki, C++ staje się preferowanym wyborem w tworzeniu oprogramowania dla systemów wbudowanych.', '2024-11-18 10:30:00', true, 2, 12),
    ('Zalety języka C++ w programowaniu niskopoziomowym', 'C++ łączy cechy programowania wysokiego poziomu z bezpośrednią kontrolą nad pamięcią, co czyni go doskonałym wyborem do programowania niskopoziomowego. Dzięki możliwości manipulacji wskaźnikami i zarządzaniu pamięcią, C++ pozwala na pisanie wyjątkowo wydajnych programów, które mogą bezpośrednio współpracować z systemem operacyjnym i sprzętem. Język C++ umożliwia dostęp do funkcji systemowych oraz pozwala na tworzenie aplikacji, które wymagają optymalizacji w zakresie pamięci i wydajności. C++ jest także szeroko stosowany w tworzeniu sterowników i systemów operacyjnych.', '2024-11-17 14:15:00', true, 3, 12),
    ('C++ w tworzeniu aplikacji dla mikrokontrolerów', 'C++ jest popularnym wyborem w programowaniu mikrokontrolerów, ponieważ oferuje pełną kontrolę nad sprzętem oraz możliwości programowania obiektowego, co ułatwia zarządzanie dużymi projektami. Mikrokontrolery są powszechnie używane w systemach wbudowanych, takich jak urządzenia IoT, systemy automatyki czy urządzenia medyczne. C++ pozwala na efektywne wykorzystanie zasobów pamięci, umożliwiając tworzenie programów, które działają na urządzeniach o ograniczonej mocy obliczeniowej. Programowanie w C++ w mikrokontrolerach pozwala również na łatwiejsze zarządzanie kodem, dzięki funkcjom takim jak klasy i dziedziczenie.', '2024-11-16 13:00:00', true, 2, 12),

    # SQL
    ('Wprowadzenie do SQL', 'SQL (Structured Query Language) to język zapytań służący do zarządzania danymi w relacyjnych bazach danych. Dzięki SQL możemy tworzyć tabele, zarządzać danymi, wykonywać zapytania oraz zapewniać integralność danych. Jednym z podstawowych elementów SQL jest możliwość tworzenia zapytań SELECT, które pozwalają na wyciąganie danych z jednej lub więcej tabel. Ponadto, SQL umożliwia modyfikację danych za pomocą poleceń INSERT, UPDATE oraz DELETE. SQL jest fundamentem dla każdego, kto chce pracować z bazami danych, niezależnie od tego, czy tworzy aplikacje webowe, czy zarządza dużymi systemami bazodanowymi.', '2024-11-19 12:00:00', true, 3, 13),
    ('Podstawowe operacje w SQL', 'W SQL podstawowe operacje na danych obejmują SELECT, INSERT, UPDATE oraz DELETE. SELECT jest używane do pobierania danych z bazy, umożliwiając określenie, które kolumny i rekordy mają zostać zwrócone. INSERT pozwala na dodawanie nowych rekordów do tabeli, natomiast UPDATE umożliwia modyfikowanie istniejących danych. DELETE pozwala na usunięcie rekordów z tabeli. Każda z tych operacji może być wzbogacona o różnorodne warunki, takie jak WHERE, aby precyzyjnie określić, które dane mają zostać wybrane, zmienione lub usunięte.', '2024-11-18 10:30:00', true, 2, 13),
    ('Łączenie wielu tabel',  'Operacja JOIN w SQL umożliwia łączenie danych z dwóch lub więcej tabel na podstawie wspólnych wartości w kolumnach. Istnieje kilka typów JOIN, takich jak INNER JOIN, LEFT JOIN, RIGHT JOIN i FULL JOIN, które różnią się sposobem łączenia danych. INNER JOIN zwraca tylko te wiersze, które mają odpowiadające im wartości w obu tabelach, podczas gdy LEFT JOIN zwraca wszystkie wiersze z lewej tabeli, a w przypadku braku dopasowania w prawej tabeli, uzupełnia je wartościami NULL. JOIN jest niezwykle użytecznym narzędziem do pracy z rozbudowanymi bazami danych, które zawierają wiele powiązanych tabel.', '2024-11-17 14:15:00', true, 3, 13),
    ('Grupowanie danych w SQL', 'Grupowanie danych w SQL jest realizowane za pomocą klauzuli GROUP BY, która pozwala na pogrupowanie wyników zapytania według jednej lub więcej kolumn. Grupowanie jest szczególnie przydatne, gdy chcemy obliczyć agregaty, takie jak suma (SUM), średnia (AVG), minimum (MIN), maksimum (MAX) czy liczba (COUNT) w obrębie różnych grup danych. Grupowanie może być wzbogacone o warunki, takie jak HAVING, które pozwalają na filtrowanie wyników już po ich pogrupowaniu, co daje dodatkową elastyczność przy pracy z danymi.', '2024-11-16 13:00:00', true, 4, 13),
    ('Indeksy w SQL', 'Indeksy w SQL to struktury danych, które przyspieszają operacje wyszukiwania i porównywania danych w tabelach. Dzięki indeksom zapytania SELECT mogą wykonywać się szybciej, zwłaszcza w przypadku dużych zbiorów danych. Indeksy są tworzone na jednej lub więcej kolumnach tabeli, co pozwala na szybkie zlokalizowanie rekordów na podstawie tych kolumn. Chociaż indeksy poprawiają wydajność odczytu danych, mogą wpłynąć na wydajność operacji zapisu, ponieważ każda zmiana w tabeli wymaga również aktualizacji indeksów. Odpowiednie zarządzanie indeksami jest kluczowe dla optymalizacji zapytań.', '2024-11-15 11:00:00', true, 5, 13),
    ('SQL a bezpieczeństwo danych', 'Bezpieczeństwo danych w SQL jest kluczowym aspektem zarządzania bazami danych. Istnieje kilka najlepszych praktyk, które pomagają chronić dane przed nieautoryzowanym dostępem. Jednym z najważniejszych narzędzi jest kontrola dostępu, która pozwala określić, kto może wykonywać operacje na bazie danych. Warto również korzystać z parametrów zapytań (prepared statements), aby zabezpieczyć aplikacje przed atakami SQL injection. Ponadto, regularne tworzenie kopii zapasowych oraz stosowanie szyfrowania danych wrażliwych są ważnymi metodami ochrony danych przed ich utratą lub kradzieżą.', '2024-11-14 09:30:00', true, 1, 13),
    ('Normalizacja w SQL',  'Normalizacja to proces organizowania danych w bazie danych w celu minimalizacji redundancji i zależności. Główne zasady normalizacji opierają się na podziale dużych tabel na mniejsze, bardziej zorganizowane jednostki, eliminując duplikację danych. Normalizacja odbywa się w kilku etapach, z których każdy odpowiada za eliminację różnych rodzajów problemów w strukturze bazy. Celem normalizacji jest poprawa integralności danych i optymalizacja działania zapytań. Z drugiej strony, zbyt zaawansowana normalizacja może prowadzić do złożoności w zapytaniach, dlatego należy znaleźć równowagę.', '2024-11-13 08:45:00', true, 2, 13),

    # Kotlin
    ('Wprowadzenie do Kotlina', 'Kotlin to nowoczesny, statycznie typowany język programowania, który stał się popularny w ekosystemie Androida. Jego celem jest bycie bardziej wyrazistym, bezpiecznym i ekspresyjnym w porównaniu do Javy. Kotlin wspiera programowanie obiektowe, funkcyjne oraz współczesne podejścia, takie jak null safety i rozszerzanie klas. Jego interoperacyjność z Javą pozwala na łatwe włączenie Kotlina do istniejących projektów. Kotlin stał się oficjalnym językiem programowania dla Androida, co sprawia, że jest idealnym wyborem dla programistów chcących tworzyć aplikacje mobilne na tę platformę.', '2024-11-19 15:00:00', true, 2, 14),
    ('Kotlin w programowaniu aplikacji mobilnych', 'Kotlin to jeden z najlepszych języków do tworzenia aplikacji mobilnych na platformę Android. Jego interoperacyjność z Javą sprawia, że można łatwo przechodzić z Javy na Kotlin, co jest dużym atutem dla istniejących projektów. Kotlin oferuje funkcje, takie jak null safety, które pozwalają na bezpieczniejsze zarządzanie danymi. Dzięki wbudowanym bibliotekam oraz wsparciu Android Jetpack, programowanie aplikacji mobilnych w Kotlinie staje się bardziej wydajne i przyjemne. Kotlin jest także przyszłościowym językiem dla Androida, a Google oficjalnie wspiera go w swoich narzędziach.', '2024-11-18 12:30:00', true, 3, 14),
    ('Zalety Kotlina w aplikacjach mobilnych', 'Kotlin ma wiele zalet, które sprawiają, że jest idealnym językiem do tworzenia aplikacji mobilnych na Androida. Po pierwsze, dzięki składni, która jest prostsza niż Java, programiści mogą pisać kod szybciej i łatwiej. Kolejną zaletą jest pełne wsparcie dla nowoczesnych paradygmatów programowania, jak programowanie funkcyjne. Kotlin posiada również wbudowane funkcje ochrony przed błędami, takie jak null safety, co redukuje liczbę błędów w aplikacjach mobilnych. Kotlin ma także bogaty ekosystem bibliotek, które przyspieszają proces tworzenia aplikacji mobilnych.', '2024-11-17 14:00:00', true, 3, 14),

    # Swift
    ('Wprowadzenie do Swifta', 'Swift to nowoczesny język programowania opracowany przez Apple, który jest używany do tworzenia aplikacji na iOS, macOS, watchOS i tvOS. Swift oferuje prostą składnię, która jest jednocześnie potężna, co sprawia, że jest łatwiejszy w nauce i użyciu niż jego poprzednik, Objective-C. Swift wspiera programowanie obiektowe, funkcyjne oraz współczesne podejścia, takie jak opcjonalne typy i silne typowanie, co minimalizuje błędy podczas kompilacji. Dzięki wsparciu Apple i stale rozwijającemu się ekosystemowi, Swift stał się fundamentem dla aplikacji mobilnych na urządzenia Apple.', '2024-11-19 16:00:00', true, 4, 15),
    ('Swift w programowaniu aplikacji mobilnych', 'Swift jest językiem zdominowującym rozwój aplikacji na platformy Apple, szczególnie iOS. Jego nowoczesna składnia oraz silna integracja z frameworkiem UIKit sprawiają, że tworzenie aplikacji na iPhone\'a i iPada staje się bardziej efektywne i przyjemne. Swift oferuje wiele wbudowanych narzędzi, takich jak automatyczne zarządzanie pamięcią i opcjonalne typy, które pomagają w tworzeniu bezpiecznych aplikacji mobilnych. Dzięki temu, że Swift jest w pełni wspierany przez Apple, programiści mogą być pewni, że ich aplikacje będą kompatybilne z najnowszymi wersjami iOS.', '2024-11-18 13:30:00', true, 4, 15),
    ('Zalety Swifta w aplikacjach mobilnych', 'Swift stał się popularnym wyborem dla programistów tworzących aplikacje mobilne na platformy Apple. Jego szybkość, bezpieczeństwo i łatwość użycia sprawiają, że jest preferowanym językiem do tworzenia aplikacji iOS. Dzięki silnemu systemowi typów, Swift pomaga uniknąć wielu typowych błędów programistycznych. Dodatkowo, nowoczesne funkcje takie jak automatyczne zarządzanie pamięcią oraz wsparcie dla rozwoju aplikacji przy użyciu SwiftUI sprawiają, że programowanie w Swift jest bardziej efektywne. Swift to również język, który jest stale rozwijany przez Apple, co oznacza, że programiści mogą liczyć na wsparcie i najnowsze funkcje.', '2024-11-17 16:30:00', true, 4, 15);

INSERT INTO comments
    (user_id, username, email, content, created_at, post_id)
VALUES
    # Java
    (4, null, null, 'Java jest świetnym językiem, ale mam wrażenie, że staje się coraz bardziej przestarzała w porównaniu z nowoczesnymi technologiami, jak Kotlin czy TypeScript. Mimo to, wciąż ma swoje miejsce, szczególnie w aplikacjach korporacyjnych', '2024-11-18 14:00:00', 1),
    (2, null, null, 'Doskonały wpis, czekam na kolejne artykuły.', '2024-11-19 23:15:00', 1),
    (3, null, null, 'Jako programista Java, muszę przyznać, że choć ten język jest potężny, to jego rozmiar i złożoność sprawiają, że praca nad projektami może być przytłaczająca. Dodatkowo, Java wciąż nie nadąża za nowoczesnymi trendami, jak np. programowanie funkcyjne.', '2024-11-20 00:02:00', 1),
    (null, 'StackGuru', 'stackguru@stackmail.pl', 'Używam Javy od lat i wciąż uważam ją za najlepszy wybór do aplikacji korporacyjnych. Nie wyobrażam sobie pracy bez Springa i Hibernate, które naprawdę ułatwiają życie. Co więcej, społeczność Javy jest fenomenalna, zawsze znajdziesz rozwiązanie na problemy.', '2024-11-23 11:00:00', 1),

    (null, 'BitByBit', 'bitbybit@techblog.pl', 'Kolekcje w Javie to absolutna podstawa! Praca z ArrayList czy HashMap ułatwia życie programistom. Ostatnio zrobiłem projekt, w którym użyłem TreeSet i sprawdził się świetnie do przechowywania danych w porządku rosnącym. Zdecydowanie polecam każdemu programiście opanowanie tej biblioteki!.', '2024-11-24 09:45:00', 3),
    (4, null, null, 'Zastanawia mnie, jak można to wdrożyć w praktyce?', '2024-11-24 11:30:00', 3),
    (1, null, null, 'Moim zdaniem kolekcje to coś, co każdy programista Javy musi znać na wylot. Dobre zrozumienie różnicy między ArrayList a LinkedList pozwala podejmować lepsze decyzje projektowe i unikać wielu błędów w dużych projektach.', '2024-11-25 11:30:00', 3),
    (3, null, null, 'Kolekcje w Javie są tak wszechstronne! Ostatnio wykorzystałem PriorityQueue do implementacji algorytmu, który musiał szybko wybierać najmniejsze wartości z dużej ilości danych. To narzędzie sprawdziło się świetnie. Java nie bez powodu jest tak popularna wśród programistów.', '2024-11-25 12:30:00', 3),

    (1, null, null, 'Bardzo szczegółowy i wyczerpujący artykuł, super robota!', '2024-11-19 19:00:00', 5),
    (2, null, null, 'Mam pytanie: czy można to zastosować w innych dziedzinach?', '2024-11-20 19:00:00', 5),
    (null, 'KamilDev', 'kamil.dev@wp.pl', 'Spring Boot rzeczywiście upraszcza życie programisty, zwłaszcza dzięki wbudowanej konfiguracji. Zdecydowanie przyspiesza rozwój aplikacji. Czasami jednak te automatyczne konfiguracje mogą sprawiać problemy, kiedy potrzeba bardziej zaawansowanego dostosowania. Mimo to, jest to jeden z najlepszych frameworków w Javie.', '2024-11-23 14:00:00', 5),
    (4, null, null, 'Świetne podejście do omawianego tematu, bardzo mnie to zaciekawiło.', '2024-11-24 19:00:00', 5),
    (null, 'AniaCode', 'ania.code@o2.pl', 'Mam pytanie: korzystacie z jakichś dodatkowych rozszerzeń do Spring Boot, które pomagają w rozwoju aplikacji? Zauważyłam, że domyślna konfiguracja często wymaga pewnych poprawek, a chciałabym dowiedzieć się, jakie są najlepsze praktyki do rozszerzania możliwości frameworku.', '2024-11-26 05:15:00', 5),
    (null, 'PrzemekPro', 'przemek_pro@gmail.pl', 'Jako początkujący programista, doceniam Spring Boot za łatwość rozpoczęcia pracy. To naprawdę świetny sposób, aby szybko uruchomić aplikację, ale zauważyłam, że w miarę jak projekt rośnie, muszę coraz więcej rozumieć, co dokładnie robi framework. Czy macie jakieś sugestie, jak lepiej zrozumieć jego mechanizmy?', '2024-11-26 04:15:00', 5),

    (null, 'StackGuru', 'stackguru@stackmail.pl', 'Stream API w Javie to rewolucja w sposobie pracy z danymi! Dzięki takim operacjom jak map(), filter() czy collect() kod staje się znacznie bardziej elegancki i czytelny. Zdecydowanie ułatwia to pracę, a do tego opcja pracy równoległej to ogromna zaleta przy dużych zbiorach danych.', '2024-11-19 09:00:00', 6),
    (null, 'BitByBit', 'bitbybit@techblog.pl', 'Uwielbiam Stream API! Dzięki niemu moje aplikacje stały się bardziej czytelne, a operacje na kolekcjach stały się łatwiejsze do napisania', '2024-11-21 16:27:00', 6),
    (3, null, null, 'Dzięki za inspirację, to bardzo pomaga w mojej pracy.', '2024-11-22 16:55:00', 6),
    (null, 'TomekJava', 'tomek.java@wp.pl', 'Stream API to jedno z najlepszych narzędzi, które zostały wprowadzone do Javy. Łatwość w przetwarzaniu danych i eliminowanie tradycyjnych pętli sprawiają, że kod staje się o wiele bardziej przejrzysty. A opcja pracy równoległej? To naprawdę ogromny plus!', '2024-11-23 13:15:00', 6),
    (null, 'JuliaTech', 'julia.tech@wp.pl', 'Zgadzam się z wszystkimi pozytywnymi opiniami o Stream API. Dzięki temu narzędziu moje aplikacje stały się bardziej eleganckie, a operacje na kolekcjach są o wiele łatwiejsze do napisania. Dodatkowo, optymalizacja dzięki parallelStream() to świetna funkcjonalność!', '2024-11-24 08:00:00', 6),


    (4, null, null, 'Spring Boot to świetne narzędzie, które znacząco przyspiesza rozwój aplikacji, ale czasami mam wrażenie, że przez swoją „magiczność” może ukrywać zbyt wiele za kulisami. Dla początkujących programistów to może być problematyczne, bo tracą możliwość pełnego zrozumienia działania aplikacji.', NOW(), 7),
    (null, 'ElaC', 'ela.c@interia.pl', 'Spring Boot zdecydowanie upraszcza życie programistom, ale jego rozbudowany zestaw funkcji może być przytłaczający. Czasami jest za dużo abstrakcji, przez co trudno znaleźć najlepsze rozwiązanie w przypadku specyficznych problemów, a dokumentacja bywa niejednoznaczna.', '2024-11-26 01:45:00', 7),

    ( 1, null, null, 'Spring Data JPA to niesamowite narzędzie, które naprawdę upraszcza pracę z bazami danych. Działa idealnie z PostgreSQL, a konfiguracja w pliku application.properties jest tak prosta, że można od razu zacząć pracę nad logiką aplikacji. To bardzo wygodne rozwiązanie.', '2024-11-19 10:00:00', 8),
    (2, null, null, 'Spring Boot naprawdę upraszcza zarządzanie bazami danych. Działa świetnie z PostgreSQL, a konfiguracja jest tak łatwa, że mogę się skupić na samej logice aplikacji. Transakcje są bardzo wygodne, bo wiem, że moje operacje na bazie będą spójne i bezpieczne.', '2024-11-20 11:30:00', 8),
    (4, null, null, 'Miałem problemy z konfiguracją baz danych w innych frameworkach, ale Spring Boot całkowicie to zmienił. Dzięki Spring Data JPA mogłem szybko połączyć aplikację z bazą, a dodatkowo automatyczna konfiguracja w application.properties to ogromna oszczędność czasu. Polecam!', '2024-11-21 09:15:00', 8),
    (null, 'ScriptMaven', 'scriptmaven@freelancer.dev', 'Mam pytanie: czy mogę to wykorzystać w swojej pracy?', '2024-11-22 19:15:00', 8),
    (null, 'JakubCoder', 'jakub.coder@wp.pl', 'Zgadzam się! Spring Boot z Spring Data JPA i Flyway to super połączenie, które oszczędza dużo czasu. Automatyczna konfiguracja pozwala szybko połączyć się z bazą danych, a transakcje sprawiają, że całość jest stabilna i bezpieczna. Praca z bazą danych w tym frameworku jest naprawdę łatwa.', '2024-11-21 10:05:00', 8),
    (null, 'KarolinaCoder', 'karolina.coder@interia.pl', 'Dzięki Spring Boot mogłam łatwo połączyć moją aplikację z PostgreSQL. Spring Data JPA robi całą robotę, a ja mogę skupić się na innych aspektach aplikacji. Jestem zachwycona prostotą i szybkością pracy z bazą danych, zwłaszcza przy użyciu Flyway.', '2024-11-23 11:00:00', 8),

    (null, 'ScriptMaven', 'scriptmaven@freelancer.dev', 'Spring Security umożliwia implementację wielu metod uwierzytelniania w łatwy sposób. Dzięki wbudowanej obsłudze JWT i OAuth2, integracja z zewnętrznymi systemami uwierzytelniania jest szybka i prosta. Ochrona przed atakami CSRF i XSS to świetny bonus!', '2024-11-21 13:00:00', 9),
    (null, 'StackGuru', 'stackguru@stackmail.pl', 'Dzięki Spring Boot i Spring Security mogłam bardzo szybko zaimplementować mechanizmy uwierzytelniania w aplikacji. Obsługa JWT oraz OAuth2 sprawiły, że proces logowania stał się prosty, a jednocześnie bardzo bezpieczny. Świetne rozwiązanie do zabezpieczania aplikacji.', '2024-11-22 11:30:00', 9),
    (null, 'BitByBit', 'bitbybit@techblog.pl', 'Ciekawy wpis, zwłaszcza końcowe wnioski. Ochrona przed atakami CSRF i XSS to kluczowy element w zabezpieczaniu aplikacji.', '2024-11-23 10:20:00', 9),

    # PHP
    (3, null, null, 'Czy możesz polecić jakieś źródła do dalszego zgłębiania tematu?', '2024-11-22 12:05:00', 11),
    (4, null, null, 'Super wpis, czekam na więcej.', '2024-11-23 18:56:00', 11),

    (1, null, null, 'PDO to świetne narzędzie do pracy z bazami danych w PHP! Używanie zapytań przygotowanych to klucz do zapewnienia bezpieczeństwa aplikacji. Zdecydowanie polecam korzystać z PDO zamiast tradycyjnych metod komunikacji z bazą danych.', '2024-11-19 08:30:00', 12),
    (4, null, null, 'Zgadzam się, PDO to bardzo bezpieczna metoda pracy z bazami danych w PHP. Dzięki zapytaniom przygotowanym, możemy uniknąć wielu potencjalnych problemów, takich jak SQL Injection.', '2024-11-20 10:45:00', 12),
    (3, null, null, 'PDO to świetny wybór do pracy z bazami danych w PHP. Używanie zapytań przygotowanych daje duże poczucie bezpieczeństwa, a sama konfiguracja jest bardzo prosta. Polecam każdemu, kto chce pisać bezpieczne aplikacje z PHP.', '2024-11-23 11:30:00', 12),

    (2, 3, 20, 'Zdecydowanie JIT to jedna z najważniejszych zmian w PHP 8.1.', '2024-11-22 16:06:00', 13),
    (1, 1, 20, 'Cieszę się, że PHP rozwija się w kierunku nowoczesnych rozwiązań.', '2024-11-22 23:59:00', 13),
    (null, 'BitByBit', 'bitbybit@techblog.pl', 'Czy są jakieś materiały, które wyjaśniają implementację Enums w PHP?', '2024-11-23 15:02:00', 13),

    (null, 'BitByBit', 'bitbybit@techblog.pl', 'Laravel to mój ulubiony framework. Blade i Eloquent to połączenie idealne.', '2024-11-18 19:12:00', 14),
    (null, 'ScriptMaven', 'scriptmaven@freelancer.dev', 'Dokumentacja Laravela naprawdę ułatwia start nowym użytkownikom.', '2024-11-21 03:43:00', 14),
    (1, null, null, 'Czy Laravel wspiera wszystkie bazy danych, czy są jakieś ograniczenia?', '2024-11-22 07:52:00', 14),

    (1, null, null, 'Dzięki sesjom moje aplikacje stały się znacznie bardziej użyteczne.', '2024-11-18 12:10:54', 15),
    (null, 'StackGuru', 'stackguru@stackmail.pl', 'Ciekawy wpis! Czy możesz wyjaśnić, jak PHP zarządza plikami sesji na serwerze?', '2024-11-20 19:28:00', 15),
    (3, null, null, 'Czy w sesjach w PHP można przechowywać duże ilości danych, czy lepiej użyć bazy?', '2024-11-22 22:17:00', 15),

    (4, null, null, 'Operator "match" to naprawdę wygodna alternatywa dla "switch".', '2024-11-20 12:10:54', 16),
    (null, 'BitByBit', 'bitbybit@techblog.pl', 'Named Arguments to coś, czego brakowało mi w PHP od dawna.', '2024-11-20 13:56:00', 16),
    (null, 'ScriptMaven', 'scriptmaven@freelancer.dev', 'JIT przyspieszył moje skrypty bardziej, niż się spodziewałem.', '2024-11-22 21:15:00', 16),
    (3, null, null, 'Świetne podsumowanie nowości! PHP idzie w dobrą stronę.', '2024-11-23 07:54:00', 16),
    (null, 'nick', 'test@gmail.com', '<strong>Testowy komentarz</strong><br /><em>Testowy komentarz2</em>', '2024-11-24 00:10:54', 16),

    ##############################
    # HTML
    (null, 'CodeLover', 'code.lover@outlook.com', 'Bardzo dobrze wyjaśniona struktura dokumentu. Przyda się początkującym!', 'NOW()', 18),
    (null, 'HTMLJoe', 'joe123@gmail.com', 'Krótko, ale treściwie! Idealny materiał dla startujących w webdev.', '2024-11-24 10:40:00', 18),

    (null, 'AnnaNowak', 'anna.nowak@gmail.com', 'Bardzo przydatne wyjaśnienie, szczególnie dla osób, które dopiero zaczynają tworzyć formularze!', '2024-11-24 11:00:00', 19),
    (null, 'Krzysiek89', 'krzysiek89@yahoo.com', 'Nie wspomniałeś o walidacji danych w formularzach, czy planujesz osobny post na ten temat?', '2024-11-24 11:15:00', 19),
    (null, 'MartaWeb', 'marta.web@hotmail.com', 'Fajny wpis, ale może dodałbyś przykład z użyciem <input type="password">? To też jest ważny element formularzy.', '2024-11-24 11:30:00', 19),
    (null, 'Janek123', 'janek123@o2.pl', 'Szczerze mówiąc, brakuje tu bardziej praktycznych przykładów. Sam opis działania to trochę za mało.', '2024-11-24 11:45:00', 19),
    (null, 'OlaDev', 'ola.dev@wp.pl', 'Dzięki za ten wpis! Zawsze miałam problem z różnicą między GET a POST, może opiszesz to szerzej?', '2024-11-24 12:00:00', 19),

    (1, null, null, 'Świetnie, że wspominasz o czytnikach ekranowych! Semantyczne tagi to klucz do lepszej dostępności.', '2024-11-24 12:30:00', 21),
    (null, 'TomekSEO', 'tomek.seo@wp.pl', 'Czy używanie semantycznych tagów naprawdę aż tak wpływa na SEO? Masz może jakieś dowody lub źródła?', '2024-11-24 12:45:00', 21),
    (3, null, null, 'Dobry wpis, ale brakuje mi przykładu praktycznego, jak zamienić zwykłe &lt;div&gt; na semantyczne tagi.', '2024-11-24 13:00:00', 21),
    (2, null, null, 'Zdecydowanie popieram używanie semantycznych tagów. Ułatwia to późniejszą pracę z CSS i JS.', '2024-11-24 13:15:00', 21),
    (null, 'Janek123', 'janek123@o2.pl', 'Dzięki za ten post! Często zapominam o &lt;section&gt;, mimo że to świetny sposób na organizację treści.', '2024-11-24 13:30:00', 21),

    (null, 'ŁukaszWeb', 'lukas.programowanie@gmail.com', 'Ciekawy wpis, ale brakuje mi przykładów kodu z użyciem <canvas> – mógłbyś coś takiego dodać?', '2024-11-24 15:00:00', 22),

    (4, null, null, 'Bardzo dobry wpis. SEO w obrazach jest często pomijane, a ma ogromne znaczenie.', '2024-11-22 16:00:00', 24),
    (null, 'MaciekFrontend', 'maciek.frontend@yahoo.com', 'Mam pytanie: co zrobić, jeśli obraz jest tylko dekoracyjny? Czy alt powinien być wtedy pusty?', '2024-11-23 06:07:00', 24),
    (1, null, null, 'Dzięki za ten post! Dobre opisy alt są kluczowe dla dostępności, ale zauważyłam, że wiele osób wciąż to ignoruje.', '2024-11-24 16:30:00', 24),

    # CSS
    (3, null, null, 'Świetne podsumowanie! Zastanawiam się, jak CSS Grid wypada w porównaniu do Flexboxa. Kiedy najlepiej używać jednego lub drugiego?', '2024-11-24 17:00:00', 26),
    (null, 'AgnieszkaCode', 'agnieszka.code@yahoo.com', 'Wspaniałe narzędzie, ale na początku trochę trudne do opanowania. Może dodasz przykład kodu dla początkujących?', '2024-11-24 17:30:00', 26),
    (null, 'Janek123', 'janek123@o2.pl', 'CSS Grid to game-changer! Projektowanie responsywnych układów stało się o wiele prostsze.', '2024-11-24 17:45:00', 26),
    (null, 'AnnaNowak', 'anna.nowak@gmail.com', 'Mam pytanie – czy można używać CSS Grid w połączeniu z Flexboxem w jednym projekcie? Jakie są ograniczenia?', '2024-11-24 18:00:00', 26),
    (4, null, null, 'W teorii Grid wygląda świetnie, ale w praktyce ciężko go czasem dopasować do bardziej dynamicznych treści.', '2024-11-24 18:15:00', 26),

    (3, null, null, 'Czy Flexbox ma jakieś ograniczenia w porównaniu do CSS Grid? Zastanawiam się, które narzędzie jest lepsze w jakich sytuacjach.', '2024-11-24 19:30:00', 27),
    (null, 'ŁukaszWeb', 'lukas.programowanie@gmail.com', 'Wcześniej używałem float, ale odkąd poznałem Flexbox, nie wyobrażam sobie powrotu do starych metod.', '2024-11-24 20:15:00', 27),
    (null, 'TomekSEO', 'tomek.seo@wp.pl', 'Ciekawy wpis! Jak myślisz, czy Flexbox z czasem wyprze inne techniki układów, czy zawsze będzie współistnieć z Gridem?', '2024-11-24 21:00:00', 27),
    (null, 'StackGuru', 'stackguru@stackmail.pl', 'Flexbox jest niesamowity! Po kilku godzinach nauki w końcu zrozumiałam, jak działa justify-content.', '2024-11-24 21:30:00', 27),

    (1, null, null, 'Warto dodać, że Media Queries świetnie współpracują z Flexboxem i Gridem, co jeszcze bardziej ułatwia tworzenie responsywnych stron.', '2024-11-19 22:15:00', 30),
    (3, null, null, 'Mam pytanie – czy używacie Media Queries do każdego elementu na stronie, czy tylko do całych sekcji?', '2024-11-21 12:54:00', 30),
    (null, 'Krzysiek89', 'krzysiek89@yahoo.com', 'Czy Media Queries mają jakieś ograniczenia w przypadku starszych wersji przeglądarek?', '2024-11-24 23:45:00', 30),
    (null, 'OlaDev', 'ola.dev@wp.pl', 'Media Queries są fundamentem responsywnego designu, ale niektóre projekty wymagają ich bardziej zaawansowanego użycia.', '2024-11-25 00:15:00', 30),


    (null, 'KasiaDesign99', 'kasia.design@gmail.com', 'Cześć! Mam pytanie – jak najlepiej organizować pliki SASS w dużych projektach? Używacie osobnych plików dla zmiennych, mixinów, itp.?', '2024-11-23 08:30:00', 31),
    (null, 'BartekDev', 'bartek.dev@o2.pl', 'SASS świetnie się sprawdza, ale dla małych projektów może być przesadą. Używam go głównie w większych aplikacjach, gdzie struktura jest bardziej skomplikowana.', '2024-11-23 10:15:00', 31),

    # JavaScript
    (null, 'PawełJS', 'pawel_js@o2.pl', 'jQuery było świetnym rozwiązaniem przez długi czas, ale teraz coraz częściej lepiej sięgnąć po jakiś framework. Osobiście sięgam po Reacta. Czasami jednak nadal korzystam z jQuery w mniejszych projektach, gdzie nie potrzebuję pełnej aplikacji SPA.', '2024-11-24 10:30:00', 36),
    (null, 'AniaFrontend', 'aneczka.frontend@wp.pl', 'Zgadza się, jQuery bardzo uprościło życie programistów, ale teraz React i Angular rządzą. Ciekawi mnie, czy jQuery może mieć jeszcze jakieś zastosowanie w 2025 roku?', '2024-11-25 10:45:00', 36),
    (null, 'KasiaWeb', 'kasia.web@interia.pl', 'Chociaż jQuery nie jest już na topie, to jego prostota wciąż sprawia, że jest idealnym rozwiązaniem dla małych stron i aplikacji. Czasami wracam do niego, gdy trzeba szybko coś zrobić.', '2024-11-25 11:15:00', 36),
    (null, 'OlaDev', 'ola.dev@wp.pl', 'To prawda, jQuery znacznie ułatwia manipulowanie DOM. Z drugiej strony, z Reactem czy Angular można zrobić więcej, zwłaszcza w większych projektach, gdzie jQuery może stać się zbyt ciężkie.', '2024-11-25 11:30:00', 36),
    (4, null, null, 'Mam wrażenie, że jQuery to już przeszłość. Zdecydowanie React czy Vue to przyszłość. Chociaż jQuery wciąż ma swoje miejsce w starszych aplikacjach.', '2024-11-23 11:45:00', 36),
    (null, 'PatrykDev', 'patryk.dev@wp.pl', '@ariprz Nie zgadzam się, jQuery ma swoje zastosowanie tam, gdzie nie trzeba budować całych aplikacji. Dzięki niemu proste strony działają szybko i płynnie.', '2024-11-25 12:00:00', 36),
    (null, 'ŁukaszWeb', 'lukas.programowanie@gmail.com', 'Fajny post! Ja nadal używam jQuery w niektórych projektach, szczególnie przy animacjach i prostych interakcjach. Choć React i Angular to potężne narzędzia, jQuery nie jest jeszcze całkowicie martwe.', '2024-11-25 12:15:00', 36),
    (null, 'BitByBit', 'bitbybit@techblog.pl', 'Chociaż jQuery miało swoje najlepsze lata, dla nowych projektów zalecam korzystanie z nowoczesnych frameworków. Ale czasami warto wrócić do jQuery, zwłaszcza przy prostych stronach.', '2024-11-25 12:45:00', 36),

    (null, 'AniaFrontend', 'aneczka.frontend@wp.pl', 'Zgadzam się, React to świetna biblioteka do tworzenia dynamicznych aplikacji. Jego wirtualny DOM to duża zaleta, szczególnie w przypadku dużych aplikacji. Dodatkowo, ekosystem Reacta jest naprawdę potężny, co ułatwia pracę.', '2024-11-18 13:00:00', 37),
    (null, 'KamilJS', 'kamil.js@interia.pl', 'React rzeczywiście zdominował rynek aplikacji webowych. Dzięki komponentom łatwiej jest utrzymać porządek w projekcie, a także dodać nowe funkcjonalności w sposób szybki i zorganizowany.', '2024-11-19 13:15:00', 37),
    (null, 'KasiaWeb', 'kasia.web@interia.pl', 'W React korzystam od kilku miesięcy i jestem pod wrażeniem jego wydajności. Dzięki wirtualnemu DOM zmiany na stronie są bardzo szybkie, co poprawia UX. Mam nadzieję, że w przyszłości będziemy widzieć jeszcze więcej rozwoju tej biblioteki.', '2024-11-20 13:30:00', 37),
    (4, null, null, 'React zdominował rynek, ale warto też zwrócić uwagę na alternatywy jak Vue.js, które również oferują świetne rozwiązania do tworzenia interfejsów użytkownika. Niemniej jednak, React to nadal mój wybór, ze względu na jego popularność i wsparcie społeczności.', '2024-11-20 15:15:00', 37),

    (null, 'ŁukaszWeb', 'lukas.programowanie@gmail.com', 'Angular jest jednym z najlepszych frameworków, jeśli chodzi o tworzenie dużych aplikacji. Dzięki dwukierunkowemu powiązaniu danych i silnemu wsparciu TypeScriptu, łatwiej zarządzać kodem i jego strukturą.', '2024-11-20 09:30:00', 38),

    (null, 'OlaDev', 'ola.dev@wp.pl', 'Vue.js to naprawdę przyjazny framework. Dzięki jego prostej składni, nauka jest szybka, a integracja z istniejącymi projektami naprawdę prosta. Moim zdaniem, jest to doskonały wybór zarówno dla początkujących, jak i do większych aplikacji.', '2024-11-25 18:00:00', 39),
    (1, null, null, 'Vue.js to bardzo elastyczny framework. Jego zaletą jest łatwa integracja z istniejącymi aplikacjami, co sprawia, że jest to świetne rozwiązanie, kiedy chcesz poprawić funkcjonalność starego projektu.', '2024-11-25 18:45:00', 39),
    (null, 'AgnieszkaCode', 'agnieszka.code@yahoo.com', 'Jako programista, cenię Vue.js za to, że łączy w sobie najlepsze cechy Reacta i Angulara, ale jest lżejszy i łatwiejszy do nauki. Możliwość stopniowego wdrażania go w istniejących projektach jest dużą zaletą.', '2024-11-25 19:15:00', 39),
    (null, 'NataliaVue', 'natalia.vue@outlook.com', 'Jestem wielką fanką Vue.js! Prosta składnia, świetna dokumentacja i możliwość rozwoju aplikacji krok po kroku. Idealny wybór do budowania zarówno prostych, jak i bardziej złożonych aplikacji.', '2024-11-25 20:00:00', 39),

    # TypeScript
    (null, 'ŁukaszWeb', 'lukas.programowanie@gmail.com', 'Jako programista webowy nie wyobrażam sobie pracy bez DOM. Dzięki niemu mogę tworzyć dynamiczne strony, które są interaktywne i łatwe do aktualizacji. Manipulowanie elementami HTML za pomocą JavaScript to klucz do sukcesu w aplikacjach webowych.', '2024-11-25 22:45:00', 35),

    (null, 'ŁukaszWeb', 'lukas.programowanie@gmail.com', 'Jako programista JavaScript, zauważyłam ogromną różnicę po przesiadce na TypeScript. Silne typowanie i mechanizmy obiektowe znacznie poprawiają organizację kodu, co jest szczególnie ważne w dużych aplikacjach.', '2024-11-20 15:15:00', 41),
    (null, 'AniaFrontend', 'aneczka.frontend@wp.pl', 'TypeScript poprawia jakość kodu i umożliwia wykrywanie błędów przed uruchomieniem aplikacji. Typowanie i wsparcie dla OOP to coś, co ułatwia zarządzanie dużymi projektami i współpracę z innymi programistami.', '2024-11-21 00:45:00', 41),
    (3, null, null, 'TypeScript to must-have w dużych aplikacjach. Dzięki temu, że mogę pracować z klasami, interfejsami i silnym typowaniem, rozwój aplikacji jest bardziej uporządkowany i bezpieczniejszy, co czyni TypeScript bardzo dobrym wyborem do dużych projektów.', '2024-11-21 01:15:00', 41);